### ISSUE TITLE
Hand model off by about 45 degrees in Oculus Quest

### ISSUE THREAD

**Issue by m-ender** [De-Panther/unity-webxr-export#110]
When loading into WebXR on a Quest (either directly in the Oculus Browser, or through Oculus Link from a PC), the hand models seem to point 45 degree upwards from where they should be. I'm not seeing this issue with an HTC Vive. I don't know if this problem is with the plugin, WebXR or Oculus's OpenXR runtime, but is there a way this plugin could take this discrepancy into account? Alternatively, is there a way to determine which headset is actually being used while WebXR is active, so I could apply a rotation manually?

**Comment by De-Panther** [comment]
Does this issue happen to you with this sample?
https://de-panther.github.io/unity-webxr-export/

WebXR Export use the `gripSpace` and not `targetRaySpace` for controllers poses.

The issue is that `gripSpace` is align with the pose of the hand that holds the controller, while (I think) `targetRaySpace` is align with the tracker of the controller.
I know that currently there's a bug when using Oculus Link, where the `targetRaySpace` rotation has an offset of 90 degrees on one of the axis.

I want to track both `gripSpace` and `targetRaySpace`, to let the developer switch between them according to the needs.
This should solve your issue in most cases. (But as I wrote, currently Oculus Link has a bug there)

WebXR Export has support for Input Profiles, so on web(doesn't emulate well on the editor), you can get the controller profile name.
https://github.com/De-Panther/webxr-input-profiles-loader
https://developer.mozilla.org/en-US/docs/Web/API/XRInputSource/gripSpace
https://developer.mozilla.org/en-US/docs/Web/API/XRInputSource/targetRaySpace

**Comment by m-ender** [comment]
In the sample, it actually loads up the controller model (whereas in our app, we just get the hand models currently). There's a split second in the sample before it switches from hand to controller, and the hand model seems to be off, too (but the controller model is correctly aligned with the physical controller). That said, there's no ray in the sample, so I can't tell which way that would point. I'll look into what we need to do to load up the correct model instead of the generic hands though.

And thanks for pointing me towards the input profiles and the controller pose spaces, I'm sure we can make some progress with that.

**Comment by De-Panther** [comment]
In the sample, you can uncheck the use of Input Profiles Loader, there's a checkbox at the top.

If you want to use the Input Profiles Loader in your project, you need to import the package. https://openupm.com/packages/com.de-panther.webxr-input-profiles-loader/

**Comment by m-ender** [comment]
Thanks for your replies, we managed to get it working by using the Input Profiles Loader and then manually rotating our laser pointer if the loaded profiles is an Oculus Touch.

**Comment by wlewis55** [comment]
Also hand this same problem, where in the sample the hands were 45 degrees off (down/away from user) and the oculus touch controllers were correct. When I set this up in Unity, the hands were correct, and the controllers were 45 off in the opposite direction (up/towards user). I'm using a Quest Gen1 to test.

**Comment by De-Panther** [comment]
WebXR has `gripSpace`, Unity doesn't.
The models of the Input Profiles are based on the `gripSpace`, so I don't have a way to position them correctly in the editor.
I think that in the editor I'll fallback to the general controller of the Input Profiles, instead of checking if the controller is Oculus Touch.
And I'm currently setting `targetRaySpace` to be the default for the controllers, instead of `gripSpace`.
