### ISSUE TITLE
webXR namespace can't be found

### ISSUE THREAD

**Issue by abuti-shuti** [De-Panther/unity-webxr-export#123]
code I write can't access the WebXR functions (for example webXRController.GetButton(WebXRController.ButtonTypes.ButtonA) ), Unity can't find the namespace. Does this have to do something with webXR being inside the Packages 'folder'.

by the way, great asset! 👍

**Comment by De-Panther** [comment]
Use Assembly Definition file (`.asmdef`), and reference the WebXR asmdef from there.
https://docs.unity3d.com/Manual/class-AssemblyDefinitionImporter.html
Right click on your script folder, Create Assembly Definition file, and in the "Assembly Definition References" section select the `WebXR.asmdef` file.

Thanks

**Comment by abuti-shuti** [comment]
Thanks, it works now

**Comment by Lt23live** [comment]
I dont know much about assembly definitions but when i do this it fixes the errors but causes many of my other scripts to break/not connect with each other.

**Comment by De-Panther** [comment]
@Lt23live it's a Unity issue, read more about assembly definitions and better ask in the relevant Unity forums. e.g. the Unity Scripting forum https://forum.unity.com/forums/scripting.12/

**Comment by Lt23live** [comment]
@De-Panther   thank you for the fast reply. The fact that this has its own definition it is most definitely locked out from the rest of Unity. It does make it extremely difficult to implement a usage of your SDK in my code base.  Is there a reason this required its own Assembly?

**Comment by De-Panther** [comment]
Sorry, but I don't want to repeat Unity's manual.
https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html
There are enough reasons there to why use it.

I can understand why it may be difficult for you to use it, but it's an essential part of Unity, all the packages of Unity are using it, and some of them are setting the "Auto Referenced" check to false, just like this package.

Better learn how to use it. Not for this package.

**Comment by Lt23live** [comment]
I think I can see the appeal for speed recompilation but a framework such as this should never be self-contained because it would be referenced too much and used in conjunction with other plugins. 

You say all of the packages are using it and I agree but somehow I am able to access them from the basic Assembly-CSharp scripts. 

An alternate solution would be to copy the Editor and Runtime folder out of the Packages location, into the project somewhere (e.g. Assets/WebXR) and remove the package in the package manager. After that delete the .asmdef files from both the Editor and Runtime folders. After doing that I was able to access the files from Assembly-CSharp scripts. 

This is an astounding plugin by the way! Great job.

**Comment by De-Panther** [comment]
The solution should be to use asmdef in your project :)

If you want to edit stuff in the package, it would be simpler for you to copy the packages to the project Packages folder. There you can set "Auto Referenced" true in the asmdef files of the copied package.

You are able to use packages which are set to "Auto Referenced" true. It's not a good practice.
