### ISSUE TITLE
Can't see WebXR namespace when using package management

### ISSUE THREAD

**Issue by dracolytch** [De-Panther/unity-webxr-export#137]
Hey, this package management thing is a nightmare. Couldn't find any way to reference the WebXR scripts from my Unity project (2019.1.5f1). Had to copy the scripts out of the library cache into my project so that my code could reference them. This whole alternate package manager has been, frankly, an unusable mess. Recommend just reverting back to .unitypackage files.

**Comment by De-Panther** [comment]
This project supports 2019.4.7 and up (I recommend 2020.3 cycle for now), it doesn't supports 2019.1.
The 2019.4 cycle has useful tools for the UPM, like a window to set custom Scoped Registries, and option to show the packages in those scopes.
To reference classes in this package, you need to add Assembly Definition asset to your scripts folder, and reference the WebXR asmdef file.

Those might be new concepts, but once you learn them, they are useful and powerful tools.

Separating scripts to asmdef files(with no auto reference), means that only assemblies that you use are compiled.
Using UPM keep your assets folder cleaner, and make updating packages much more simple.

**Comment by dracolytch** [comment]
So far, the exporter has worked in 2019.3, from a technical standpoint (which makes sense, given how the x.4 releases are supposed to be x.3 releases with refinements).

I was able to add the scoped registry via a text editor... But frankly even the OpenUPM registry isn't well documented on how to use it. The idea is sound, but the whole thins is just not very usable yet.

One of the things I **like** about Unity is the fact that, for the most part, all of the scripts are there to be edited. I don't like having that abstracted away. I appreciate that everything is in a namespace, but if I need to modify behavior, I can't just go adjust scripts to how I see fit. I have to either subclass (if the source package will let me),  edit things in the package cache (a terrible idea), or copy the package cache out and remove the assembly definitions (a hassle).

Don't get me wrong, this is a great project, and the work you've done is first-rate. The package manager thing is actually the biggest hurdle to using this stuff.

**Comment by De-Panther** [comment]
It may work in older versions, but it's not supported. Also, in newer versions Unity improved lots of related features, like rendering, WebGL bug fixes, and UPM. That's why I'm currently recommend using the 2020 LTS.

Newer versions has better tools for UPM, and it's much more easier to manage than using `.unitypackage` files.
![image](https://user-images.githubusercontent.com/4749703/114727701-1b3aa880-9d47-11eb-93ae-998be3c6258e.png)
![image](https://user-images.githubusercontent.com/4749703/114727913-47562980-9d47-11eb-91ba-07d9c53bb322.png)

You can always download/clone the packages from Git, and set them as local packages. That way you'll be able to edit them.
But in my opinion it's better to build on top, instead of editing. Unless there's a bug, and then you are more than welcome to contribute bug fixes, or report bugs.
In any case, there's no reason to remove the asmdef files, just add your own asmdef file and reference those...

I'm not intending to support `.unitypackage` files distribution, it's hard to maintain both as package developer and as a developer that use the package and want to be up to date with the package.
I had some files that removed or changed names/location, and using `.unitypackage` would force me as a user to delete the package folder and re-import from scratch each time.
With UPM package it's just a click of a button.
![image](https://user-images.githubusercontent.com/4749703/114730839-e419c680-9d49-11eb-93a9-a9f3ee4c3c47.png)

Thanks

**Comment by De-Panther** [comment]
I'm closing the issue, but would be happy to keep discussing on using UPM.
