### ISSUE TITLE
Question regarding WebXRCamera swtich to AR method

### ISSUE THREAD

**Issue by TheXRMonk** [De-Panther/unity-webxr-export#142]
Any reason why in the WebXrCamera the camera switches enable/disables are made during update (using the 'switched' logic), and not just in the OnXRChange?

https://github.com/De-Panther/unity-webxr-export/blob/8ff0ba3a685605bb36a15034a270442706c0a865/Packages/webxr/Runtime/Scripts/WebXRCamera.cs#L43-L78

https://github.com/De-Panther/unity-webxr-export/blob/8ff0ba3a685605bb36a15034a270442706c0a865/Packages/webxr/Runtime/Scripts/WebXRCamera.cs#L150-L157

I'm asking cause I'm having issues with the main camera rendering on half the screen for a few seconds after toggling AR.

**Comment by De-Panther** [comment]
I don't remember what was the bug that happen when tried to switch not in update.

The few seconds of half screen render, happens because of waiting to get the first pose/view data when entering AR, while already running the Unity update loop.
A possible fix, would be to resume the Unity update loop only after we get the first pose/view data.
It all happens in the `webxr.jspre` file.

I'll try to find a time to implement it.

**Comment by TheXRMonk** [comment]
> I don't remember what was the bug that happen when tried to switch not in update.
> 
> The few seconds of half screen render, happens because of waiting to get the first pose/view data when entering AR, while already running the Unity update loop.
> A possible fix, would be to resume the Unity update loop only after we get the first pose/view data.
> It all happens in the `webxr.jspre` file.
> 
> I'll try to find a time to implement it.

Does this mean WebXRSubsystem.OnXRChange only runs after first view data? That's what I'm getting from tests.

**Comment by De-Panther** [comment]
It goes like that:
- User request XR session. it may take the device time to confirm(user need to confirm or device needs to activate XR stuff).
- We pause Unity's loop.
- XR session confirmed, now we try to get the reference space.
- We got the reference space, we resume Unity's loop.
- Each frame loop, before the Unity stuff, we check for the XR frame. once we have pose/view data, we notify Unity that XR session changed (`OnXRChange`).

The issue is, that there might be few frames in which we got reference space, but we still didn't get pose/view data.

I need to make sure, to resume Unity's loop on the first time we get pose/view data, and not when we get the reference space...

**Comment by TheXRMonk** [comment]
Alright, makes sense! 
This is not the case when exiting AR right? 

Long story short; I'm trying to open a link in a new tab while in AR. My current solution is to Toggle AR if we are in AR mode, (and not toggle if we aren't), and then open the link clicked. My understanding says that any link-opening has to be user-initiated to avoid browser pop-up blocks, which is why I've implemented this jslib;

```

public void OpenLinkJSPlugin()
	{
		if(WebXRManager.Instance.XRState == WebXRState.AR)
                {
			WebXRManager.Instance.ToggleAR();
		}
		openWindow(Link);
	}
```

Using this external lib;
```
var OpenWindowPlugin = {
    openWindow: function(link)
    {
    	var url = Pointer_stringify(link);
        document.onmouseup = function()
        {
        	window.open(url);
        	document.onmouseup = null;
        }
		
		document.ontouchend = function()
		{
        	window.open(url);
        	document.ontouchend  = null;
		}
    }
};

mergeInto(LibraryManager.library, OpenWindowPlugin);
```

I'm currently getting this error the first time I try to open the link;

![already exited error](https://user-images.githubusercontent.com/54309738/116047435-5f497980-a674-11eb-8efb-162de62f8e11.png)

But if I dismiss the error and go back into AR and then click the link again, it works (sort of). 
I guess the best way to do this would be to start a coroutine to open the link once AR has been fully exited, but this leads back to having the browser block the pop-up.

**Comment by De-Panther** [comment]
Sorry, missed your last comment here.
I never tried to open a link from WebXR AR session.
I would expect the browser to close the session and open the new page with no need from the developer to manually close the session... And as you can see in the screenshot, the error says that the XR sessions has already ended, so no need to call end session twice...

**Comment by De-Panther** [comment]
Also just changed how the OnXRChange works and how XR switch is handled in general.

- User request XR session. it may take the device time to confirm(user need to confirm or device needs to activate XR stuff).
- We pause Unity's loop.
- XR session confirmed, now we try to get the reference space.
- We got the reference space, we have temp loop that doesn't render Unity, until we have pose/view data.
- we notify Unity that XR session changed.
- we resume Unity's loop.
- `OnXRChange` is called on the first Unity Update since the XR session switch.

https://github.com/De-Panther/unity-webxr-export/pull/147

**Comment by De-Panther** [comment]
I'm closing the issue, has it's been some time since there was a comment.
If the issue still exists, please comment and we'll open it again.

Also, the issue of link opening from Unity in XR mode, sounds like an issue of general Unity WebGL + WebXR Export + Browser implementation.
So maybe a better place to talk about that would be the WebXR Discord.
