### ISSUE TITLE
Unable to use the plugin

### ISSUE THREAD

**Issue by sonalmahendru** [De-Panther/unity-webxr-export#198]
Getting compilation error on websurfacechecking.loader.js (error says: 'failed to execute compile on webassembly; incorrect response mime tye; expected: 'application/wasm').

Please help with it. I want to use your webXR plugin to deploy my models in a markerless manner upon detection of surface.

**Comment by De-Panther** [comment]
Your issue is not with WebXR Export, but with Unity WebGL.
Your server isn't configured correctly, and doesn't serve the files as it should.
You can read those pages in the Unity manual for more info:
https://docs.unity3d.com/Manual/webgl-deploying.html
https://docs.unity3d.com/Manual/webgl-server-configuration-code-samples.html
There's even more info on how to configure your server in the Unity WebGL official forum.
https://forum.unity.com/forums/webgl.84/

Also don't forget that for WebXR to work, you need to serve it from secured context. e.g. HTTPS server.
