### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by neizvedaniydag** [De-Panther/unity-webxr-export#232]
[Package Manager Window] Unable to add package [https://github.com/De-Panther/unity-webxr-export.git?path=/Packages/webxr-interactions]:
  Package com.de-panther.webxr-interactions@https://github.com/De-Panther/unity-webxr-export.git?path=/Packages/webxr-interactions has invalid dependencies or related test packages:
    com.de-panther.webxr (dependency): Package [com.de-panther.webxr@0.15.0-preview] cannot be found
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)

**Comment by De-Panther** [comment]
As written in the instructions, use OpenUPM instead of git.

https://github.com/De-Panther/unity-webxr-export/blob/master/Packages/webxr/README.md

https://github.com/De-Panther/unity-webxr-export/blob/master/Packages/webxr-interactions/README.md

It's written in big bold header, don't use git in the package manager.
