### ISSUE TITLE
Getting started with Oculus in Unity

### ISSUE THREAD

**Issue by GaryFrewin** [De-Panther/unity-webxr-export#256]
Sorry, perhaps a stupid question, but I can't figure it out. 

I am trying to give my user the choice of VR or not in my webgl project. Initially, the app loads and they are presented with Scene1, where they can use the app as they always have in a desktop/browser mode. 

If they click on a VR button on my unity UI, it takes them to scene 2, where there is a WebXRCameraSet, so I'd like it to launch in the headset. But nothing happens in the Oculus Headset when I go to scene 2. 

If I run scene 2 in play mode in Unity, it fires up on the headset. It's just when I build and deploy to my webhost, going to scene 2 doesn't trigger any launch in the headset. 

Am I missing something here? 

I've tried deploying the VR scene separately and deploying it online. I then use firefox reality from my quest to browse to the page. When I click the launch VR button, the screen shows a sbs view, but it doesn't actually go to VR, it's a square screen with 2 sbs views, and it doesn't move when the headset moves. 

Thanks

**Comment by GaryFrewin** [comment]
> Sorry, perhaps a stupid question, but I can't figure it out.
> 
> I am trying to give my user the choice of VR or not in my webgl project. Initially, the app loads and they are presented with Scene1, where they can use the app as they always have in a desktop/browser mode.
> 
> If they click on a VR button on my unity UI, it takes them to scene 2, where there is a WebXRCameraSet, so I'd like it to launch in the headset. But nothing happens in the Oculus Headset when I go to scene 2.
> 
> If I run scene 2 in play mode in Unity, it fires up on the headset. It's just when I build and deploy to my webhost, going to scene 2 doesn't trigger any launch in the headset.
> 
> Am I missing something here? Thanks

Better yet, is it possible to do this all in one scene? Toggling between xr camera and normal unity camera?

**Comment by art3miz18** [comment]
@GaryFrewin did you see any errors while firing up VR module ? In chrome or Firefox console

As it might actually be memory allocation to load another scene 
Or maybe headset fails to initialize with WebXR camera set

**Comment by GaryFrewin** [comment]
Thanks for getting back to me. :) 

When I run it on quest 2 from firefox reality, I cannot seem to find the log... 

When I run it on quest 2 using link cable / rift, I press the enter VR button on my laptop, the headset starts the loading screen, but then the console on my laptop browser says the following:

Warning: Unrecognised feature requested. Hand Tracking
and
Could not create session because an unknown error occurred. 
Here is a screen shot
![image](https://user-images.githubusercontent.com/48474558/224923384-00aa6b5c-ec2a-46e3-97eb-fd506b186ee3.png)

Presumably these are the same errors that are preventing it from loading in firefox reality too... perhaps? 

I removed hand tracking (although I do need it) in the project manager, and the first error goes away but the second one remains. This occurs on chrome, on firefox the enter VR button is always greyed out.

**Comment by De-Panther** [comment]
Lot's of related and unrelated issues.

- I never tested how the package works when it starts in a secondary scene. So I expect to unexpected issues.
- The editor doesn't activate the WebXR subsystem, as this subsystem works only on web. The editor try to activate desktop subsystems if you enabled them, e.g. OpenXR, Oculus or SteamVR subsystems.
- You can use the `WebXRCameraSet` on the first scene, and use it's `CameraMain` as your camera for the flat screen experience.
- If you want to use a number of scenes to manage resources, you can use the `WebXRCameraSet` on the first scene, and set it as `Don't destroy on load`. Or you can load the next scenes additively.
- Oculus Hand Tracking works on desktop only in the Editor, they didn't enabled it for runtime apps. So it doesn't work using desktop browsers.
- The OpenXR runtime of the Oculus Desktop App has a bug on version 49 where it has this "unknown error". You can use SteamVR OpenXR runtime, or change the settings of the Oculus Desktop App to allow beta versions and update to version 50 where it should be fixed.
- Firefox Reality is not supported since long time ago, you can use Wolvic instead.

Also, please follow the Getting Started guide and play with the Sample desert scene. It'll help you to better figure out how this package works and pinpoint errors.
https://github.com/De-Panther/unity-webxr-export/blob/master/Documentation/Getting-Started.md

**Comment by De-Panther** [comment]
Closing as there were no new comments in a while
